/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'clothing' : IDL.Null,
  'furniture' : IDL.Null,
  'appliances' : IDL.Null,
  'electronics' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'productInterest' : ProductCategory,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'clothing' : IDL.Null,
    'furniture' : IDL.Null,
    'appliances' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'productInterest' : ProductCategory,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getInquiry' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ProductCategory, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };